require('lsp.languages.vim')
require('lsp.languages.lua')
require('lsp.languages.php')
require('lsp.languages.json')
require('lsp.languages.tsserver')
require('lsp.languages.vue')
require('lsp.languages.html')
require('lsp.languages.css')
-- require('lsp.languages.efm')
require('lsp.languages.diagnosticls')
